apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}  # Name of the service
  namespace: {{ .Values.namespace | default "default" }}  # Specify the namespace
spec:
  type: {{ .Values.service.type | default "NodePort" }}  # Service type (default: NodePort)
  ports:
  - port: {{ .Values.service.port | default 4200 }}  # Service port
    targetPort: {{ .Values.service.targetPort | default 4200 }}  # Target container port
    nodePort: {{ .Values.service.nodePort | default 30000 }}  # NodePort value
  selector:
    app: {{ .Release.Name }}  # Selector for the pods 
